language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
script:
  - npm install
  - $(npm bin)/cypress run --record
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $githubToken
  local_dir: build
  on:
    branch: master
